name: Update UserName

on:
  schedule:
    - cron:  '0 15 * * *'
  workflow_dispatch:

jobs:
  post-toot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Installing dependencies using poetry
        run: poetry install --no-dev
      - name: Update UserName
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          CONSUMER_API_KEY: ${{secrets.CONSUMER_API_KEY}}
          CONSUMER_API_KEY_SECRET: ${{secrets.CONSUMER_API_KEY_SECRET}}
        run: poetry run python username_updater/username_updater.py
